name: raychat
description: A reactive chat application fueled by a Firebase Realtime Database.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  intl: 0.17.0
  provider: ^6.0.3
  firebase_core: ^1.24.0
  cloud_firestore: ^3.5.1
  firebase_auth: ^3.11.2
  firebase_core_platform_interface: 4.5.1 # note removed ^
  firebase_messaging: ^13.0.4 # previously I only had this which was pulling in 4.5.2 which you do not want

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
flutter:
  uses-material-design: true
